image:
  repository: ghcr.io/mhsanaei/3x-ui
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

replicaCount: 1

web:
  enabled: true
  type: ClusterIP
  portName: vless-web
  protocol: TCP
  port: 2053
  targetPort: 2053

  ingress:
    enabled: false
    className: ""
    annotations: {}
    tls: []
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix

vpn:
  enabled: true
  type: LoadBalancer
  portName: vless-vpn
  protocol: TCP
  port: 53705
  targetPort: 53705

proxy:
  enabled: false
  type: LoadBalancer
  portName: vless-proxy
  protocol: TCP
  port: 53710
  targetPort: 53710

secretRef: ""

resources: {}

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
